Test build and push
Signed-off-by: Travis F. Collins <travis.collins@analog.com>

diff --git a/.github/workflows/build_dev.yml b/.github/workflows/build_dev.yml
--- a/.github/workflows/build_dev.yml
+++ b/.github/workflows/build_dev.yml
@@ -15,17 +15,7 @@ jobs:
       matrix:
         project:
           [
-            "hdl",
-            "sw",
-            "libiio-debian-bullseye",
-            "libiio-ubuntu-18.04",
-            "libiio-ubuntu-20.04",
             "libiio-ubuntu-22.04",
-            "libiio-fedora-34",
-            "libiio-fedora-28",
-            "libiio-centos-7",
-            "libiio-opensuse-15.4",
-            "test-harness",
           ]
         include:
           - project: "hdl"
@@ -70,12 +60,12 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
 
-      - name: Login to DockerHub
-        if: github.ref == 'refs/heads/main'
-        uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
+      # - name: Login to DockerHub
+      #   if: github.ref == 'refs/heads/main'
+      #   uses: docker/login-action@v1
+      #   with:
+      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
+      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
 
       - name: Log in to the GitHub Container registry
         uses: docker/login-action@v1
@@ -89,66 +79,66 @@ jobs:
         uses: docker/build-push-action@v4.1.1
         with:
           file: ${{ matrix.DOCKERFILE }}
-          push: ${{ github.ref == 'refs/heads/main' }}
-          tags: tfcollins/${{ matrix.TAG_ROOT }}:latest
-
-
-  docker_arm:
-    runs-on: ubuntu-20.04
-    strategy:
-      fail-fast: false
-      matrix:
-        project: ["libiio-ubuntu-18.04", "libiio-debian-bullseye"]
-        include:
-          - project: "libiio-ubuntu-18.04"
-            DOCKERFILE: "libiio/Dockerfile-ubuntu-18.04"
-            TAG_ROOT: "libiio_ubuntu_18_04-ci-arm-ppc"
-            ARCH: linux/arm64
-            REFERENCE_IMAGE: "ubuntu:18.04"
-          - project: "libiio-debian-bullseye"
-            DOCKERFILE: "libiio/Dockerfile-debian-bullseye"
-            TAG_ROOT: "libiio_debian_bullseye-ci-arm-ppc"
-            ARCH: linux/arm64
-            REFERENCE_IMAGE: "debian:bullseye"
-
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-      - name: Login to DockerHub
-        if: github.ref == 'refs/heads/main'
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v2
-        with:
-          platforms: arm,arm64,ppc64le,s390x
-      - name: Set up Docker Buildx
-        id: buildx
-        uses: docker/setup-buildx-action@v2
-        with:
-          install: true
-          driver: docker-container
-      - name: Available platforms
-        run: echo ${{ steps.buildx.outputs.platforms }}
-
-      - name: Test build
-        run: |
-          cp Dockerfile-arm Dockerfile
-          docker buildx create --name armbuilder
-          docker buildx use armbuilder
-          docker buildx build --builder armbuilder -t test_${{ matrix.TAG_ROOT }} --platform linux/arm64 --load .
-          ARCH_CHECK=$(docker run --platform linux/arm64 test_${{ matrix.TAG_ROOT }}:latest uname -a)
-          echo "$ARCH_CHECK"
-          echo "$ARCH_CHECK" | grep -i aarch64 || exit 1
-
-      - name: Build and push
-        id: docker_build
-        uses: docker/build-push-action@v2
-        with:
           push: true
           tags: tfcollins/${{ matrix.TAG_ROOT }}:latest
-          file: Dockerfile-arm
-          context: .
-          platforms: linux/arm,linux/arm64,linux/ppc64le,linux/s390x
+
+
+  # docker_arm:
+  #   runs-on: ubuntu-20.04
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       project: ["libiio-ubuntu-18.04", "libiio-debian-bullseye"]
+  #       include:
+  #         - project: "libiio-ubuntu-18.04"
+  #           DOCKERFILE: "libiio/Dockerfile-ubuntu-18.04"
+  #           TAG_ROOT: "libiio_ubuntu_18_04-ci-arm-ppc"
+  #           ARCH: linux/arm64
+  #           REFERENCE_IMAGE: "ubuntu:18.04"
+  #         - project: "libiio-debian-bullseye"
+  #           DOCKERFILE: "libiio/Dockerfile-debian-bullseye"
+  #           TAG_ROOT: "libiio_debian_bullseye-ci-arm-ppc"
+  #           ARCH: linux/arm64
+  #           REFERENCE_IMAGE: "debian:bullseye"
+
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v2
+  #     - name: Login to DockerHub
+  #       if: github.ref == 'refs/heads/main'
+  #       uses: docker/login-action@v2
+  #       with:
+  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
+  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
+  #     - name: Set up QEMU
+  #       uses: docker/setup-qemu-action@v2
+  #       with:
+  #         platforms: arm,arm64,ppc64le,s390x
+  #     - name: Set up Docker Buildx
+  #       id: buildx
+  #       uses: docker/setup-buildx-action@v2
+  #       with:
+  #         install: true
+  #         driver: docker-container
+  #     - name: Available platforms
+  #       run: echo ${{ steps.buildx.outputs.platforms }}
+
+  #     - name: Test build
+  #       run: |
+  #         cp Dockerfile-arm Dockerfile
+  #         docker buildx create --name armbuilder
+  #         docker buildx use armbuilder
+  #         docker buildx build --builder armbuilder -t test_${{ matrix.TAG_ROOT }} --platform linux/arm64 --load .
+  #         ARCH_CHECK=$(docker run --platform linux/arm64 test_${{ matrix.TAG_ROOT }}:latest uname -a)
+  #         echo "$ARCH_CHECK"
+  #         echo "$ARCH_CHECK" | grep -i aarch64 || exit 1
+
+  #     - name: Build and push
+  #       id: docker_build
+  #       uses: docker/build-push-action@v2
+  #       with:
+  #         push: true
+  #         tags: tfcollins/${{ matrix.TAG_ROOT }}:latest
+  #         file: Dockerfile-arm
+  #         context: .
+  #         platforms: linux/arm,linux/arm64,linux/ppc64le,linux/s390x
